// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mortor.Web.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Mortor.Web.Migrations
{
    [DbContext(typeof(MortorBlazorContext))]
    [Migration("20201218131902_AddLineToReport")]
    partial class AddLineToReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Mortor.Web.Data.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Mortor.Web.Data.ReportLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportId")
                        .HasColumnType("text");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportLine");
                });

            modelBuilder.Entity("Mortor.Web.Data.ReportLine", b =>
                {
                    b.HasOne("Mortor.Web.Data.Report", null)
                        .WithMany("ReportLines")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Mortor.Web.Data.Report", b =>
                {
                    b.Navigation("ReportLines");
                });
#pragma warning restore 612, 618
        }
    }
}
